name: Cross

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      matrix:
        required: true
        type: string

jobs:
  cross:
    strategy:
      matrix: ${{fromJSON(inputs.matrix)}}
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
            working-directory: ${{ inputs.package }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: aewag/actions/cross-install@add-common-ci-patterns
      - if: ${{ matrix.features != 'NO_FEATURE' }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cross test
          --target ${{ matrix.target }}
          --no-default-features
          --features ${{ matrix.features }}
      - if: ${{ matrix.features == 'NO_FEATURE' }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cross test
          --target ${{ matrix.target }}
          --no-default-features
