name: Cross

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      matrix:
        required: true
        type: string

jobs:
  cross:
    strategy:
      matrix: ${{fromJSON(inputs.matrix)}}
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
            working-directory: ${{ inputs.package }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Install precompiled cross
        run: |
          export URL=$(curl -s https://api.github.com/repos/cross-rs/cross/releases/latest | \
            jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
          wget -O /tmp/binaries.tar.gz $URL
          tar -C /tmp -xzf /tmp/binaries.tar.gz
          mv /tmp/cross ~/.cargo/bin
      - env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cross test
          --target ${{ matrix.target }}
          --no-default-features
          --features ${{ matrix.features }}
